version: "3.7"
services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
