name: pr-lint

# pull requestで.pyが含まれていた時のみで起動する
on:
  pull_request:
    paths: '**.py'

jobs:
  pr-lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: pipenv cache
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-${{ matrix.python-version }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        path: ~/.cache/pipenv
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pipenv-
    - name: pip cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Lint files
      run: |
        git fetch --no-tags --prune --depth=1 origin ${GITHUB_HEAD_REF}
        git fetch --no-tags --prune --depth=1 origin ${GITHUB_BASE_REF}
        pipenv run pylint $(git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} --diff-filter=AM --name-only -- '*.py')
